sudo: required
services:
  - docker

script:
  - docker build -f Dockerfile.dev -t dilipagheda/confusion-react  ./
  - docker build -t dilipagheda/confusion-json-server ./json-server
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dilipagheda/confusion-react
  - docker push dilipagheda/confusion-json-server
